# This configuration is intended for production use and was created with respect to the security guide.
# The provided links to documentation guides for each property will give more information about the purpose of each property.
# security guide: https://docs.orqueio.io/manual/latest/user-guide/security/

camunda.bpm:
#  admin-user:
#    id: demo
#    password: demo
#  filter:
#    create: All tasks
# https://docs.orqueio.io/manual/latest/user-guide/security/#http-header-security-in-webapps
# https://docs.orqueio.io/manual/latest/webapps/shared-options/header-security/
  webapp:
    csrf:
      enable-same-site-cookie: true
      same-site-cookie-option: STRICT
    header-security:
      hsts-disabled: false

# https://docs.orqueio.io/manual/latest/user-guide/security/#authorization
# https://docs.orqueio.io/manual/latest/user-guide/process-engine/authorization-service/
  authorization.enabled: true

  generic-properties.properties:
# https://docs.orqueio.io/manual/latest/user-guide/security/#variable-values-from-untrusted-sources
    deserialization-type-validation-enabled: true
    deserialization-allowed-packages:
    deserialization-allowed-classes:
# https://docs.orqueio.io/manual/latest/user-guide/security/#password-policy
# https://docs.orqueio.io/manual/latest/user-guide/process-engine/password-policy/
    enable-password-policy: false

  run:
# https://docs.orqueio.io/manual/latest/user-guide/security/#authentication
# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#authentication
    auth.enabled: true
    rest.disable-wadl: true
    deployment.deploy-changed-only: true
# https://docs.orqueio.io/manual/latest/user-guide/process-engine/identity-service/#configuration-properties-of-the-ldap-plugin
# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#ldap-identity-service
# Uncomment this section to enable LDAP support for Orqueio Run
#    ldap:
#      enabled: true
#      server-url: ldaps://localhost:4334
#      administrator-group-name: orqueio-admin
#      accept-untrusted-certificates: false
#      manager-dn: uid=jonny,ou=office-berlin,o=orqueio,c=org
#      manager-password: s3cr3t
#      base-dn: o=orqueio,c=org
#      user-search-base: ''
#      user-search-filter: (objectclass=person)
#      user-id-attribute: uid
#      user-firstname-attribute: cn
#      user-lastname-attribute: sn
#      user-email-ttribute: mail
#      user-password-attribute: userpassword
#      group-search-base: ''
#      group-search-filter: (objectclass=groupOfNames)
#      group-id-attribute: cn
#      group-name-attribute: cn
#      group-member-attribute: member
#      sort-control-supported: false
# https://docs.orqueio.io/manual/latest/user-guide/process-engine/authorization-service/#the-administrator-authorization-plugin
# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#ldap-administrator-authorization
# Uncomment this section to grant administrator authorizations to an existing LDAP user or group
#    admin-auth:
#      enabled: true
#      administrator-user-name: admin
#      administrator-group-name: admins

# OAuth2/OIDC Configuration
# User synchronization and SSO logout are enabled by default.
# Uncomment below to customize (all options are true by default except sync-groups):
#  oauth2:
#    sso-logout:
#      enabled: true                          # Logout from IdP on OrqueIO logout
#      post-logout-redirect-uri: "{baseUrl}"  # Redirect after IdP logout
#    user-sync:
#      enabled: true                          # Sync users to database
#      auto-create-users: true                # Create users on first login
#      auto-update-users: true                # Update user info on each login
#      sync-groups: false                     # Sync groups from IdP (disabled by default)
#      remove-obsolete-group-memberships: false

# Spring Security OAuth2 Client Configuration (for OIDC)
# Supports multiple identity providers: Keycloak, Google, GitHub
spring.security.oauth2.client:
  registration:
    # Keycloak (local instance)
    keycloak:
      client-id: YOUR_KEYCLOAK_CLIENT_ID
      client-secret: YOUR_KEYCLOAK_CLIENT_SECRET
      scope:
        - openid
        - profile
        - email
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

    # Google OAuth2
    # To use Google: Obtain credentials from https://console.cloud.google.com
    # 1. Create project → APIs & Services → Credentials → Create OAuth 2.0 Client ID
    # 2. Set redirect URI: http://localhost:8080/login/oauth2/code/google (or https://yourdomain.com/login/oauth2/code/google for production)
    # 3. Replace CLIENT_ID and CLIENT_SECRET below
    google:
      client-id: YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com
      client-secret: YOUR_GOOGLE_CLIENT_SECRET
      scope:
        - openid
        - profile
        - email
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

    # GitHub OAuth2
    # To use GitHub: Create OAuth App at https://github.com/settings/developers
    # 1. New OAuth App → Set callback URL: http://localhost:8080/login/oauth2/code/github (or https://yourdomain.com/login/oauth2/code/github for production)
    # 2. Replace CLIENT_ID and CLIENT_SECRET below
    github:
      client-id: YOUR_GITHUB_CLIENT_ID
      client-secret: YOUR_GITHUB_CLIENT_SECRET
      scope:
        - read:user
        - user:email
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

    # Auth0 OAuth2/OIDC
    # Domain: dev-qolsre8ehh7bljdd.us.auth0.com
    auth0:
      client-id: YOUR_AUTH0_CLIENT_ID
      client-secret: YOUR_AUTH0_CLIENT_SECRET
      scope:
        - openid
        - profile
        - email
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

    # Okta OAuth2/OIDC
    # To use Okta: Create account at https://developer.okta.com
    # 1. Applications → Create App Integration → OIDC → Web Application
    # 2. Set redirect URI: http://localhost:8080/login/oauth2/code/okta
    # 3. Replace YOUR_OKTA_DOMAIN, CLIENT_ID and CLIENT_SECRET below
    okta:
      client-id: YOUR_OKTA_CLIENT_ID
      client-secret: YOUR_OKTA_CLIENT_SECRET
      scope:
        - openid
        - profile
        - email
      authorization-grant-type: authorization_code
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  provider:
    keycloak:
      issuer-uri: http://localhost:9090/realms/orqueio
      user-name-attribute: preferred_username

    # Google provider (auto-discovered from issuer-uri)
    google:
      issuer-uri: https://accounts.google.com
      user-name-attribute: email

    # GitHub provider (manual configuration - GitHub doesn't support OIDC discovery)
    github:
      authorization-uri: https://github.com/login/oauth/authorize
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
      user-name-attribute: login

    # Auth0 provider
    auth0:
      issuer-uri: YOUR_AUTH0_ISSUER_URI
      user-name-attribute: email

    # Okta provider
    okta:
      issuer-uri: YOUR_OKTA_ISSUER_URI
      user-name-attribute: email

server:
# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#https
# do not use the provided certificate in production
# SSL configuration disabled for development/testing
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: orqueio
#    key-store-type: pkcs12
#    key-alias: orqueio
#    key-password: orqueio
  port: 8080

# https://docs.orqueio.io/manual/latest/user-guide/security/#http-header-security-in-webapps
# https://docs.orqueio.io/manual/latest/webapps/shared-options/header-security/
  servlet.session.cookie:
    secure: false
    http-only: true

# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#logging
# https://docs.orqueio.io/manual/latest/user-guide/logging/#process-engine
logging:
   level.root: INFO
   file.name: logs/orqueio-bpm-run.log

# datasource configuration is required
# do not use the H2 databse in production
# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#connect-to-a-database
# https://docs.orqueio.io/manual/latest/user-guide/orqueio-bpm-run/#database
spring.datasource:
  url: jdbc:h2:./camunda-h2-test-production/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password: sa

# H2 Console Configuration
spring.h2.console:
  enabled: true
  path: /h2-console

# By default, Spring Boot serves static content from any directories called /static or /public or /resources or
# /META-INF/resources in the classpath. To prevent users from accidentally sharing files, this is disabled here by setting static locations to NULL.
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-static-content
spring.web.resources:
  static-locations: NULL